version: "3.9"
services:
  exporter:
    container_name: googleFontsExporter
    restart: unless-stopped
    build: .
    ports: 
      - "9877:9877"
    environment:
      - FETCHING_INTERVAL_SECONDS=10
      - EXPORTER_PORT=9877
    volumes:
      - ./configFile:/app/configFile
      - ./configFile/${CONFIG_FILE}:/app/configFile/targets.txt

volumes:
  configFile:

 
      